name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate Snake
        uses: Platane/snk@main
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs:
            ./assets/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Snake SVG
        run: |
          git config --local user.email "walterjiang726@gmail.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add Snake SVG" || true

